spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/deliveryhub}
    username: ${SPRING_DATASOURCE_USERNAME:deliveryhub}
    password: ${SPRING_DATASOURCE_PASSWORD:deliveryhub}
