# syntax=docker/dockerfile:1

FROM maven:3.9-eclipse-temurin-25 AS build
WORKDIR /workspace
COPY pom.xml .
COPY common common
COPY identity-service identity-service
COPY delivery-service delivery-service
COPY courier-service courier-service
COPY events-service events-service
COPY messaging-notification-service messaging-notification-service
COPY tracking-service tracking-service
COPY admin-service admin-service
ARG SERVICE_MODULE
RUN mvn -pl ${SERVICE_MODULE} -am -DskipTests package

FROM eclipse-temurin:25-jre
WORKDIR /app
ARG SERVICE_MODULE
COPY --from=build /workspace/${SERVICE_MODULE}/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
