spring.application.name=deliveryhub
server.port=8080

management.endpoints.web.exposure.include=health,info

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/deliveryhub
spring.datasource.username=deliveryhub
spring.datasource.password=deliveryhub


# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration