spring.application.name=deliveryhub
server.servlet.context-path=/api
server.port=8080

management.endpoints.web.exposure.include=health,info

spring.profiles.default=local

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT Configuration
jwt.secret=36cd8c7dd84ace459ec4e262e4aa96cd
jwt.expiration=86400000
